# Generated by Django 6.0.2 on 2026-03-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_text',
            field=models.CharField(),
        ),
    ]
