# Generated by Django 6.0.2 on 2026-03-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_address_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_text',
            field=models.TextField(),
        ),
    ]
