# Generated by Django 6.0.2 on 2026-03-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_address_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_text',
            field=models.CharField(),
        ),
    ]
