# Generated by Django 6.0.2 on 2026-03-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_address_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('shopping', 'Shopping'), ('on_the_way', 'On The Way'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
